package it.polimi.ingsw.PSP4.client.gui.sceneController;

import it.polimi.ingsw.PSP4.client.gui.FXMLFile;
import it.polimi.ingsw.PSP4.client.gui.GodGraphics;
import it.polimi.ingsw.PSP4.message.MessageType;
import it.polimi.ingsw.PSP4.message.requests.ChooseStartingPlayerRequest;
import it.polimi.ingsw.PSP4.message.requests.Request;
import javafx.event.Event;
import javafx.fxml.FXML;
import javafx.scene.Node;
import javafx.scene.layout.HBox;
import javafx.scene.layout.StackPane;
import javafx.scene.text.Text;

public class LobbyStartingPlayerSelectionControl extends GUIController {
    @FXML
    private HBox godPicturesHBox;
    @FXML
    private Text thirdPlayerButton;
    @FXML
    private Text secondPlayerButton;
    @FXML
    private Text firstPlayerButton;

    /**
     * Called from one of the starting player buttons. Takes its username and validates it
     * @param e Event generated by clicking on one of the buttons
     */
    public void sendStartingPlayer(Event e) {
        StackPane s = (StackPane) e.getSource();
        Text t = (Text) s.getChildren().get(0);
        getClient().validate(t.getText());
    }

    public void updateUI(Request req) {
        if (req.getType() == MessageType.FIRST_WORKER_PLACEMENT) {
            getClient().updateScene(FXMLFile.BOARD, req);
        } else if (req.getType() == MessageType.WAIT) {
            getClient().updateScene(FXMLFile.LOBBY_WAIT, null);
        } else {
            System.out.println(req.getType());
        }
    }

    public void setupAttributes(Request req) {
        if (req.getType() == MessageType.CHOOSE_STARTING_PLAYER) {
            ChooseStartingPlayerRequest r = (ChooseStartingPlayerRequest) req;
            firstPlayerButton.setText(r.getPlayerNames().get(0));
            secondPlayerButton.setText(r.getPlayerNames().get(1));
            if (r.getPlayerNames().size() == 3) {
                thirdPlayerButton.setText(r.getPlayerNames().get(2));
            }
            int counter = 0;
            for (String godName: r.getPlayerGods().values()) {
                Node n = godPicturesHBox.getChildren().get(counter);
                n.setStyle(GodGraphics.getGodCardBG(godName));
                counter++;
            }
        }
    }
}
